# vim ft=yaml
# travis-ci.org definition for PyHRF build (based on nipy)

# Multiple lines can be made a single "virtual line" because of the way that
# Travis munges each line before executing it to print out the exit status.
# It's okay for it to be on multiple physical lines, so long as you remember:
# - There can't be any leading "-"s - All newlines will be removed, so use
# ";"s
language: python
python:
    - 2.7

sudo: false

addons:
    apt:
        packages:
            - libatlas-dev
            - libatlas-base-dev
            - gfortran
            - libpng-dev

before_install:
    - pip install --no-index -f http://wheels2.astropy.org --trusted-host http://wheels2.astropy.org -f https://nipy.bic.berkeley.edu/scipy_installers/travis --trusted-host https://nipy.bic.berkeley.edu/scipy_installers/travis scipy "matplotlib<1.4";
    - pip install nibabel
    - pip install sympy
    - pip install nipy
    - pip install joblib
    - pip install scikit-learn
    - pip install munkres
    - pip install Pillow
    - pip install coverage
    - pip install coveralls

install:
    - python setup.py install

script:
    - nosetests --with-doctest --with-coverage --cover-package=pyhrf -v -s pyhrf

after_success:
    - coveralls
